[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend"
]

[start]
cmd = "npm run start --prefix backend"